server:
  port: 5051
spring:
  #  rabbitmq:
  #    host: localhost
  #    port: 5672
  #    username: user
  #    password: root
  #  zipkin:
  #    enabled: true
  #    base-url: http://localhost:9411
  #    service:
  #      name: user-service
  data:
    mongodb:
      host: localhost
      port: 27020
      username: movieappuser
      password: 12345
      database: movieapp
#  security:
#    user:
#      name: kullanici
#      password: 12345